### PR TITLE
Add an option to call API only in chat files

### PR DESCRIPTION
**Pull request by szw**
I found sending just any file to the Chat GPT API with one command/hotkey too easy. This option limits the command/hotkey usage to "chat" files. The chat files are recognized by the frontmatter having the model field with `"gpt"` string inside.

### CODE REVIEW

**Comment by bramses** [comment]
Hi @szw, thanks for the PR! Many people use ChatGPT MD in their existing notes outside of the `chat` folder. See relevant conversation about whether or not ChatGPT should work in existing notes here: https://github.com/bramses/chatgpt-md/discussions/44 and please make your case there!

**Comment by szw** [comment]
Hi @bramses! My problem was that if I accidentally pressed the `call-chatgpt-api` hotkey (without any divider), the whole note was sent to Chat GPT API. And that could lead to leaking potentially sensitive information. That's why I added the option to prevent this behavior.

**Comment by bramses** [comment]
Ah yeah I see your point. Ok cool, I'll add it as a toggle setting in an upcoming release to require "chat" key in frontmatter if not in the chats folder

**Comment by szw** [comment]
I am closing this one in favor of #47. #47 allows for more flexibility using Chat GPT inside regular notes while preventing accidental calls. If the option is enabled, at least one divider is necessary to trigger a new Chat GPT API call. The text above the divider is removed from the context.

**Pull request closed without merging**
